### PR TITLE
pyspnego 0.9.2: Rebuild

### PR DESCRIPTION
**Pull request by skupr-anaconda**
**Current package info**

| Channel | Downloads | Version | Platforms | License |
| --- | --- | --- | --- | --- |
| main | [Anaconda Downloads](https://anaconda.org/main/pyspnego) | [Anaconda Version](https://anaconda.org/main/pyspnego) | [Anaconda Platforms](https://anaconda.org/main/pyspnego) | Anaconda License |

**Destination channel:** defaults

### Links

- [PKG-4531](https://anaconda.atlassian.net/browse/PKG-4531)
- release-notes: https://github.com/jborean93/pyspnego/releases
- release-notes-tagged: https://github.com/jborean93/pyspnego/releases/tag/v0.9.2
- changelog: https://github.com/jborean93/pyspnego/blob/main/CHANGELOG.md
- license: https://github.com/jborean93/pyspnego/blob/main/LICENSE
- requirements-tagged:
  - https://github.com/jborean93/pyspnego/blob/v0.9.2/pyproject.toml

### Explanation of changes:

- Bump the build number to 1
- Use compiler and cython only on win64
- Pin cython with range >=0.29.29,<3.0.0. cython 3.x+ isn't compatible
- Remove s390x selector for ruamel.yaml as it's already available on this platform

### Notes:

- Instead of updating to 0.10.2 it was decided to rebuild `pyspnego 0.9.2` with `run_constrained` correctly identifying `pykrb5` instead of `krb5`. It's because while building a dependency `sspilib` for **pyspnego 0.10.2** I got this error on `win64`: `src\sspilib\raw\_security_buffer.c(27311): error C2065: 'SECBUFFER_CERTIFICATE_REQUEST_CONTEXT': undeclared identifier` and it looks like the upstream bug.

[PKG-4531]: https://anaconda.atlassian.net/browse/PKG-4531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by JamesRobertsonGames — APPROVED** [review]
Looks good to me! :+1:

**Review by SC426 — APPROVED** [review]

**Review by JeanChristopheMorinPerso — COMMENTED** [review]
@skupr-anaconda If it doesn't take too long, I think we should run the tests to make sure that it works with the dependencies.

**Comment by skupr-anaconda** [comment]
> @skupr-anaconda If it doesn't take too long, I think we should run the tests to make sure that it works with the dependencies.

All packages of https://github.com/jborean93 that rely on krb5 require [k5test](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/requirements-test.txt#L3 ) for testing (it's imported mainly in [conftest.py](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/tests/conftest.py#L14)). I can try pip install it and test the package

**Comment by JeanChristopheMorinPerso** [comment]
> > @skupr-anaconda If it doesn't take too long, I think we should run the tests to make sure that it works with the dependencies.
> 
> All packages of https://github.com/jborean93 that rely on krb5 require [k5test](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/requirements-test.txt#L3) for testing (it's imported mainly in [conftest.py](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/tests/conftest.py#L14)). I can try pip install it and test the package

From what I see, it's an optional test dependency, see https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/tests/conftest.py#L12-L16.

**Comment by skupr-anaconda** [comment]
> > > @skupr-anaconda If it doesn't take too long, I think we should run the tests to make sure that it works with the dependencies.
> > 
> > 
> > All packages of https://github.com/jborean93 that rely on krb5 require [k5test](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/requirements-test.txt#L3) for testing (it's imported mainly in [conftest.py](https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/tests/conftest.py#L14)). I can try pip install it and test the package
> 
> From what I see, it's an optional test dependency, see https://github.com/jborean93/pyspnego/blob/e3db11f9fee26b513eaf7e4305580fe3da7d0d6a/tests/conftest.py#L12-L16.

You're right. It is much more dependent on another package [pykrb5](https://github.com/jborean93/pykrb5/blob/e93744bc3405be56c49a5cbfbc1601412c87d54a/tests/conftest.py#L7)

**Comment by JeanChristopheMorinPerso** [comment]
And we do have pykrb5 right?

**Comment by skupr-anaconda** [comment]
> And we do have pykrb5 right?

Not yet, I'm building it https://github.com/AnacondaRecipes/pykrb5-feedstock/pull/1

**Comment by skupr-anaconda** [comment]
@JeanChristopheMorinPerso I've added tests but skipped some tests on `win64` because of the `"spnego.exceptions.InvalidTokenError: The logon attempt failed"`

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Pull request merged**
